[global]
target = "beta"

[env]
CC="x86_64-pc-linux-gnu-gcc"
CXX="x86_64-pc-linux-gnu-g++"
CPP="x86_64-pc-linux-gnu-cpp"
AS="x86_64-pc-linux-gnu-as"
AR="x86_64-pc-linux-gnu-ar"
LD="x86_64-pc-linux-gnu-ld"

[repositories.stable]
url = "https://stable.raven-os.org"

[repositories.beta]
url = "https://beta.raven-os.org"

[repositories.unstable]
url = "https://unstable.raven-os.org"
